module.exports = [
    // Macedonian Cyrillic
    "код", "кодот", "кодов", "кодон", "функција", "функцијата", "функцијава", "функцијана", 
    "променлива", "променливата", "променливава", "променливана", "класа", "класата", "класава", "класана",
    "јамка", "јамката", "јамкава", "јамкана", "ако", "инаку", "низа", "низата", "низава", "низана",
    "објект", "објектот", "објектов", "објектон", "стринг", "стрингот", "стрингов", "стрингон",
    "цел број", "булијан", "точно", "неточно", "увези", "извези",
    "конзола", "конзолата", "конзолава", "конзолана", "логирај", "компајлирај", "стартувај", "изврши", "врати",
    "циклус", "циклусот", "циклусов", "циклусон", "испечати", "тест", "тестот", "тестов", "тестон",
    "алгоритам", "алгоритмот", "алгоритмов", "алгоритмон", "влез", "влезот", "влезов", "влезон",
    "излез", "излезот", "излезов", "излезон", "програма", "програмата", "програмава", "програмана",
    "девелопер", "девелоперот", "девелоперов", "девелоперон", "софтвер", "софтверот", "софтверов", "софтверон",
    "хардвер", "хардверот", "хардверов", "хардверон", "логика", "логиката", "логикава", "логикана",
    "бубачка", "бубачката", "бубачкава", "бубачкана", "поправи", "грешка", "грешката", "грешкава", "грешкана",
    "предај", "предизвик", "предизвикот", "предизвиков", "предизвикон", "ИДЕ", "уредувач", "уредувачот", "уредувачов", "уредувачон",
    "терминал", "терминалот", "терминалов", "терминалон", "тастатура", "тастатурата", "тастатурава", "тастатурана",
    "грешка при компајлирање", "синтакса", "синтаксата", "синтаксава", "синтаксана",
    "фрејмворк", "фрејмворкот", "фрејмворков", "фрејмворкон", "база на податоци", "сервер", "серверот", "серверов", "серверон",
    "клиент", "клиентот", "клиентов", "клиентон", "јазик", "јазикот", "јазиков", "јазикон",
    "платформа", "платформата", "платформава", "платформана", "апликација", "апликацијата", "апликацијава", "апликацијана",
    "интерфејс", "интерфејсот", "интерфејсов", "интерфејсон", "библиотека", "библиотеката", "библиотекава", "библиотекана",
    "структура", "структурата", "структурава", "структурана", "метод", "методот", "методов", "методон",
    "конструктор", "конструкторот", "конструкторов", "конструкторон", "база", "базата", "базава", "базана",
    "податоци", "запис", "записот", "записов", "записон", "изјава", "изјавата", "изјавава", "изјавана",
    "прашање", "прашањето", "прашањево", "прашањено", "решение", "решението", "решениево", "решениено",
    "корисник", "корисникот", "корисников", "корисникон", "форма", "формата", "формава", "формана",
    "задаток", "задатокот", "задатоков", "задатокон", "веб", "страница", "страницата", "страницава", "страницана",
    "линк", "линкот", "линков", "линкон", "барање", "барањето", "барањево", "барањено",
    "одговор", "одговорот", "одговоров", "одговорон", "алатка", "алатката", "алаткава", "алаткана",
    "список", "списокот", "списоков", "списокон", "јсон", "клуч", "клучот", "клучов", "клучон",
    "вредност", "вредноста", "вредностава", "вредностана", "влезни податоци", "излезни податоци",
    "гит", "гитхаб", "функционалност", "функционалноста", "функционалностава", "функционалностана",
    "коментар", "коментарот", "коментаров", "коментарон", "објаснување", "објаснувањето", "објаснувањево", "објаснувањено",
    "решавање", "решавањето", "решавањево", "решавањено", "дефинирање", "дефинирањето", "дефинирањево", "дефинирањено",
    "дебагирање", "дебагирањето", "дебагирањево", "дебагирањено",
    // Додадени нови зборови
    "сортирање", "сортирањето", "сортирањево", "сортирањено", "пребарување", "пребарувањето", "пребарувањево", "пребарувањено",
    "филтрирање", "филтрирањето", "филтрирањево", "филтрирањено", "мапирање", "мапирањето", "мапирањево", "мапирањено",
    "итерација", "итерацијата", "итерацијава", "итерацијана", "рекурзија", "рекурзијата", "рекурзијава", "рекурзијана",
    "матрица", "матрицата", "матрицава", "матрицана", "табела", "табелата", "табелава", "табелана",
    "ред", "редот", "редов", "редон", "колона", "колоната", "колонава", "колонана",
    "индекс", "индексот", "индексов", "индексон", "должина", "должината", "должинава", "должинана",
    "големина", "големината", "големинава", "големинана", "размер", "размерот", "размеров", "размерон",
    "парола", "паролата", "паролава", "паролана", "корисничко име", "најава", "најавата", "најавава", "најавана",
    "одјава", "одјавата", "одјавава", "одјавана", "сесија", "сесијата", "сесијава", "сесијана",
    "токен", "токенот", "токенов", "токенон", "криптирање", "криптирањето", "криптирањево", "криптирањено",
    "валидација", "валидацијата", "валидацијава", "валидацијана", "провера", "проверата", "проверава", "проверана",
    "условие", "условието", "условиево", "условиено", "критериум", "критериумот", "критериумов", "критериумон",
    "параметар", "параметарот", "параметаров", "параметарон", "аргумент", "аргументот", "аргументов", "аргументон",
    "повратна вредност", "исклучок", "исклучокот", "исклучоков", "исклучокон", "фрлање грешка", "справување со грешки",
    "оптимизација", "оптимизацијата", "оптимизацијава", "оптимизацијана", "перформанси", "брзина", "брзината", "брзинава", "брзинана",
    "меморија", "меморијата", "меморијава", "меморијана", "простор", "просторот", "просторов", "просторон",
    "време", "времето", "времево", "времено", "бинарно", "хексадецимално", "децимално",
    "бит", "битот", "битов", "битон", "бајт", "бајтот", "бајтов", "бајтон",
    "мегабајт", "мегабајтот", "мегабајтов", "мегабајтон", "гигабајт", "гигабајтот", "гигабајтов", "гигабајтон",
    "компресија", "компресијата", "компресијава", "компресијана", "декомпресија", "декомпресијата", "декомпресијава", "декомпресијана",
    "енкодирање", "енкодирањето", "енкодирањево", "енкодирањено", "декодирање", "декодирањето", "декодирањево", "декодирањено",
    "хеш", "хешот", "хешов", "хешон", "шифрирање", "шифрирањето", "шифрирањево", "шифрирањено",
    "примерок", "примерокот", "примероков", "примерокон", "инстанца", "инстанцата", "инстанцава", "инстанцана",
    "наследување", "наследувањето", "наследувањево", "наследувањено", "енкапсулација", "енкапсулацијата", "енкапсулацијава", "енкапсулацијана",
    "полиморфизам", "полиморфизмот", "полиморфизмов", "полиморфизмон", "абстракција", "абстракцијата", "абстракцијава", "абстракцијана",
    "модул", "модулот", "модулов", "модулон", "пакет", "пакетот", "пакетов", "пакетон",
    "именски простор", "скоп", "скопот", "скопов", "скопон", "видливост", "видливоста", "видливостава", "видливостана",
    "статично", "динамично", "јавно", "приватно", "заштитено", "константа", "константата", "константава", "константана",
    "статистика", "статистиката", "статистикава", "статистикана", "анализа", "анализата", "анализава", "анализана",
    "извештај", "извештајот", "извештајов", "извештајон", "графикон", "графиконот", "графиконов", "графиконон",
    "дијаграм", "дијаграмот", "дијаграмов", "дијаграмон", "визуелизација", "визуелизацијата", "визуелизацијава", "визуелизацијана",
    "тестирање", "тестирањето", "тестирањево", "тестирањено", "единечен тест", "интеграциски тест", "функционален тест",
    "автоматизација", "автоматизацијата", "автоматизацијава", "автоматизацијана", "скрипта", "скриптата", "скриптава", "скриптана",
    "макро", "макрото", "макрово", "макроно", "команда", "командата", "командава", "командана", "аргументи од командна линија",
    "конфигурација", "конфигурацијата", "конфигурацијава", "конфигурацијана", "поставувања", "опции", "флаг", "флагот", "флагов", "флагон",
    "прекинувач", "прекинувачот", "прекинувачов", "прекинувачон", "режим", "режимот", "режимов", "режимон",
    "развој", "развојот", "развојов", "развојон", "производство", "производството", "производствово", "производствено",
    "верзија", "верзијата", "верзијава", "верзијана", "ревизија", "ревизијата", "ревизијава", "ревизијана",
    "комит", "комитот", "комитов", "комитон", "гранка", "гранката", "гранкава", "гранкана",
    "спојување", "спојувањето", "спојувањево", "спојувањено", "конфликт", "конфликтот", "конфликтов", "конфликтон",
    "резолуција", "резолуцијата", "резолуцијава", "резолуцијана", "репозиториум", "репозиториумот", "репозиториумов", "репозиториумон",
    "документација", "документацијата", "документацијава", "документацијана", "упатство", "упатството", "упатствово", "упатствено",
    "помош", "поможта", "поможава", "поможана", "водич", "водичот", "водичов", "водичон",
    "туторијал", "туторијалот", "туторијалов", "туторијалон", "пример", "примерот", "примеров", "примерон",
    "демо", "демото", "демово", "демоно", "макета", "макетата", "макетава", "макетана",
    "прототип", "прототипот", "прототипов", "прототипон", "шема", "шемата", "шемава", "шемана",
    "модел", "моделот", "моделов", "моделон", "архитектура", "архитектурата", "архитектурава", "архитектурана",
    "дизајн", "дизајнот", "дизајнов", "дизајнон", "образец", "образецот", "образецов", "образецон",
    "шаблон", "шаблонот", "шаблонов", "шаблонон", "темплејт", "темплејтот", "темплејтов", "темплејтон",
    "стил", "стилот", "стилов", "стилон", "тема", "темата", "темава", "темана",
    "изглед", "изгледот", "изгледов", "изгледон", "копче", "копчето", "копчево", "копчено",
    "поле", "полето", "полево", "полено", "мени", "менито", "менево", "менено",
    "навигација", "навигацијата", "навигацијава", "навигацијана", "рути", "страни",
    "компонента", "компонентата", "компонентава", "компонентана", "виџет", "виџетот", "виџетов", "виџетон",
    "елемент", "елементот", "елементов", "елементон", "атрибут", "атрибутот", "атрибутов", "атрибутон",
    "својство", "својството", "својствово", "својствено", "событие", "событието", "wydarzениево", "събитиено",
    "ракувач", "ракувачот", "ракувачов", "ракувачон", "колбек", "колбекот", "колбеков", "колбекон",
    "промисе", "промисето", "промисево", "промисено", "асинхроно", "синхроно",
    "мрежа", "мрежата", "мрежава", "мрежана", "протокол", "протоколот", "протоколов", "протоколон",
    "порта", "портата", "портава", "портана", "хост", "хостот", "хостов", "хостон",
    "домен", "доменот", "доменов", "доменон", "УРЛ", "патека", "патеката", "патекава", "патекана",
    "праметри", "заглавја", "телото на барањето", "статус код", "успех", "успехот", "успехов", "успехон",

    // Macedonian Latin
    "kod", "kodot", "kodov", "kodon", "funkcija", "funkcijata", "funkcijava", "funkcijana", 
    "promenliva", "promenlivata", "promenlivava", "promenlivana", "klasa", "klasata", "klasava", "klasana",
    "jamka", "jamkata", "jamkava", "jamkana", "ako", "inaku", "niza", "nizata", "nizava", "nizana",
    "objekt", "objektot", "objektov", "objekton", "string", "stringot", "stringov", "stringon",
    "cel broj", "bulijan", "tochno", "netochno", "uvezi", "izvezi",
    "konzola", "konzolata", "konzolava", "konzolana", "logiraj", "kompajliraj", "startuvaj", "izvrshi", "vrati",
    "ciklus", "ciklusot", "ciklusov", "cikluson", "ispečati", "test", "testot", "testov", "teston",
    "algoritam", "algoritmot", "algoritmov", "algoritmon", "vlez", "vlezot", "vlezov", "vlezon",
    "izlez", "izlezot", "izlezov", "izlezon", "programa", "programata", "programava", "programana",
    "developer", "developerot", "developerov", "developeron", "softver", "softverot", "softverov", "softveron",
    "hardver", "hardverot", "hardverov", "hardveron", "logika", "logikata", "logikava", "logikana",
    "bubačka", "bubačkata", "bubačkava", "bubačkana", "popravi", "greška", "greškata", "greškava", "greškana",
    "predaj", "predizvik", "predizvikot", "predizvikov", "predizvikonn", "IDE", "ureduvač", "ureduvačot", "ureduvačov", "ureduvačon",
    "terminal", "terminalot", "terminalov", "terminalon", "tastatura", "tastaturata", "tastaturava", "tastaturana",
    "greška pri kompajliranje", "sintaksa", "sintaksata", "sintaksava", "sintaksana",
    "frejmvork", "frejmvorkot", "frejmvorkov", "frejmvorkon", "baza na podatoci", "server", "serverot", "serverov", "serveron",
    "klient", "klientot", "klientov", "klienton", "jazik", "jazikot", "jazikov", "jazikon",
    "platforma", "platformata", "platformava", "platformana", "aplikacija", "aplikacijata", "aplikacijava", "aplikacijana",
    "interfejs", "interfejsot", "interfejsov", "interfejson", "biblioteka", "bibliotekata", "bibliotekava", "bibliotekana",
    "struktura", "strukturata", "strukturava", "strukturana", "metod", "metodot", "metodov", "metodon",
    "konstruktor", "konstruktorot", "konstruktorov", "konstruktoron", "baza", "bazata", "bazava", "bazana",
    "podatoci", "zapis", "zapisot", "zapisov", "zapison", "izjava", "izjavata", "izjavava", "izjavana",
    "prašenje", "prašenjeto", "prašenjevo", "prašenjeno", "rešenje", "rešenjeto", "rešenjevo", "rešenjeno",
    "korisnik", "korisnikot", "korisnikov", "korisnikon", "forma", "formata", "formava", "formana",
    "zadatok", "zadatokot", "zadatokov", "zadatokon", "web", "stranica", "stranicata", "stranicava", "stranicana",
    "link", "linkot", "linkov", "linkon", "baranje", "baranjeto", "baranjevo", "baranjeno",
    "odgovor", "odgovorot", "odgovorov", "odgovoron", "alatka", "alatkata", "alatkava", "alatkana",
    "spisok", "spiskot", "spiskov", "spiskon", "json", "ključ", "ključot", "ključov", "ključon",
    "vrednost", "vrednoста", "vrednostava", "vrednostana", "vlezni podatoci", "izlezni podatoci",
    "git", "github", "funkcionalnost", "funkcionalnoста", "funkcionalnostava", "funkcionalnostana",
    "komentar", "komentarot", "komentarov", "komentaron", "objasnuvanje", "objasnuvanjeto", "objasnuvanjevo", "objasnuvanjeno",
    "rešavanje", "rešavanjeto", "rešavanjevo", "rešavanjeno", "definiranje", "definirajeto", "definirajevo", "definirajeno",
    "debugiranje", "debugiranjeto", "debugiranjevo", "debugiranjeno",
    // Dodadeni novi zborovi
    "sortiranje", "sortiranjeto", "sortiranjevo", "sortiranjeno", "prebaruvanje", "prebaruvanjeto", "prebaruvanjevo", "prebaruvanjeno",
    "filtriranje", "filtriranjeto", "filtriranjevo", "filtriranjeno", "mapiranje", "mapiranjeto", "mapiranjevo", "mapiranjeno",
    "iteracija", "iteracijata", "iteracijava", "iteracijana", "rekurzija", "rekurzijata", "rekurzijava", "rekurzijana",
    "matrica", "matricata", "matricava", "matricana", "tabela", "tabelata", "tabelava", "tabelana",
    "red", "redot", "redov", "redon", "kolona", "kolonata", "kolonava", "kolonana",
    "indeks", "indeksot", "indeksov", "indekson", "dolžina", "dolžinata", "dolžinava", "dolžinana",
    "golemina", "goleminata", "goleminava", "goleminana", "razmer", "razmerot", "razmerov", "razmeron",
    "parola", "parolata", "parolava", "parolana", "korisničko ime", "najava", "najavata", "najavava", "najavana",
    "odjava", "odjavata", "odjavava", "odjavana", "sesija", "sesijata", "sesijava", "sesijana",
    "token", "tokenot", "tokenov", "tokenon", "kriptiranje", "kriptiranjeto", "kriptiranjevo", "kriptiranjeno",
    "validacija", "validacijata", "validacijava", "validacijana", "provera", "proverata", "proverava", "proverana",
    "uslovie", "uslovieto", "uslovievo", "uslovieno", "kriterium", "kriteriumot", "kriteriumov", "kriteriumon",
    "parametar", "parametarot", "parametarov", "parametaron", "argument", "argumentot", "argumentov", "argumenton",
    "povratna vrednost", "isklučok", "isklučokot", "isklučokov", "isklučokon", "frlanje greška", "spravuvanje so greški",
    "optimizacija", "optimizacijata", "optimizacijava", "optimizacijana", "performansi", "brzina", "brzinata", "brzinava", "brzinana",
    "memorija", "memorijata", "memorijava", "memorijana", "prostor", "prostorot", "prostorov", "prostoron",
    "vreme", "vremeto", "vremevo", "vremeno", "binarno", "heksadecimalno", "decimalno",
    "bit", "bitot", "bitov", "biton", "bajt", "bajtot", "bajtov", "bajton",
    "megabajt", "megabajtot", "megabajtov", "megabajton", "gigabajt", "gigabajtot", "gigabajtov", "gigabajton",
    "kompresija", "kompresijata", "kompresijava", "kompresijana", "dekompresija", "dekompresijata", "dekompresijava", "dekompresijana",
    "enkodiranje", "enkodiranjeto", "enkodiranjevo", "enkodiranjeno", "dekodiranje", "dekodiranjeto", "dekodiranjevo", "dekodiranjeno",
    "heš", "hešot", "hešov", "hešon", "šifriranje", "šifriranjeto", "šifriranjevo", "šifriranjeno",
    "primerok", "primerokot", "primerokov", "primerokon", "instanca", "instancata", "instancava", "instancana",
    "nasleduvanje", "nasleduvanjeto", "nasleduvanjevo", "nasleduvanjeno", "enkapsulacija", "enkapsulacijata", "enkapsulacijava", "enkapsulacijana",
    "polimorfizam", "polimorfizmot", "polimorfizmov", "polimorfizmon", "apstrakcija", "apstrakcijata", "apstrakcijava", "apstrakcijana",
    "modul", "modulot", "modulov", "modulon", "paket", "paketot", "paketov", "paketon",
    "imenski prostor", "skop", "skopot", "skopov", "skopon", "vidlivost", "vidlivosta", "vidlivostava", "vidlivostana",
    "statično", "dinamično", "javno", "privatno", "zaštiteno", "konstanta", "konstantata", "konstantava", "konstantana",
    "statistika", "statistikata", "statistikava", "statistikana", "analiza", "analizata", "analizava", "analizana",
    "izveštaj", "izveštajot", "izveštajov", "izveštajon", "grafikon", "grafikonot", "grafikonov", "grafikonon",
    "dijagram", "dijagramot", "dijagramov", "dijagramon", "vizuelizacija", "vizuelizacijata", "vizuelizacijava", "vizuelizacijana",
    "testiranje", "testiranjeto", "testiranjevo", "testiranjeno", "edinečen test", "integraciski test", "funkcionalen test",
    "avtomatizacija", "avtomatizacijata", "avtomatizacijava", "avtomatizacijana", "skripta", "skriptata", "skriptava", "skriptana",
    "makro", "makroto", "makrovo", "makrono", "komanda", "komandata", "komandava", "komandana", "argumenti od komandna linija",
    "konfiguracija", "konfiguracijata", "konfiguracijava", "konfiguracijana", "postavuvanja", "opcii", "flag", "flagot", "flagov", "flagon",
    "prekinuvač", "prekinuvačot", "prekinuvačov", "prekinuvačon", "režim", "režimot", "režimov", "režimon",
    "razvoj", "razvojot", "razvojov", "razvojon", "proizvodstvo", "proizvodstvoto", "proizvodstvovo", "proizvodstvono",
    "verzija", "verzijata", "verzijava", "verzijana", "revizija", "revizijata", "revizijava", "revizijana",
    "komit", "komitot", "komitov", "komiton", "granka", "grankata", "grankava", "grankana",
    "spojuvanje", "spojuvanjeto", "spojuvanjevo", "spojuvanjeno", "konflikt", "konfliktot", "konfliktov", "konflikton",
    "rezolucija", "rezolucijata", "rezolucijava", "rezolucijana", "repozitorium", "repozitoriumot", "repozitoriumov", "repozitoriumon",
    "dokumentacija", "dokumentacijata", "dokumentacijava", "dokumentacijana", "upatstvo", "upatstvoto", "upatstvovo", "upatstvono",
    "pomoš", "pomošta", "pomošava", "pomošana", "vodič", "vodičot", "vodičov", "vodičon",
    "tutorial", "tutorialot", "tutorialov", "tutorialon", "primer", "primerot", "primerov", "primeron",
    "demo", "demoto", "demovo", "demono", "maketa", "maketata", "maketava", "maketana",
    "prototip", "prototipot", "prototipov", "prototipon", "šema", "šemata", "šemava", "šemana",
    "model", "modelot", "modelov", "modelon", "arhitektura", "arhitekturata", "arhitekturава", "arhitekturana",
    "dizajn", "dizajnot", "dizajnov", "dizajnon", "obrazec", "obrazecot", "obrazecov", "obrazecon",
    "šablon", "šablonot", "šablonov", "šablonon", "templejt", "templejtot", "templejtov", "templejton",
    "stil", "stilot", "stilov", "silon", "tema", "temata", "temava", "temana",
    "izgled", "izgledot", "izgledov", "izgledon", "kopče", "kopčeto", "kopčevo", "kopčeno",
    "forma", "formata", "formava", "formana", "pole", "poleto", "polevo", "poleno", "lista", "listata", "listava", "listana", 
    "meni", "menito", "menevo", "meneno", "navigacija", "navigacijata", "navigacijava", "navigacijana", "ruti", "strani",
    "komponenta", "komponentata", "komponentava", "komponentana", "vidžet", "vidžetot", "vidžetov", "vidžeton",
    "element", "elementot", "elementov", "elementon", "atribut", "atributot", "atributov", "atributon",
    "svojstvo", "svojstvoto", "svojstvovo", "svojstvono", "vrednost", "vrednoста", "vrednostava", "vrednostana",
    "sobytie", "sobytajeto", "sobytiјevo", "sobytiјeno", "rakuvač", "rakuvačot", "rakuvačov", "rakuvačon", 
    "kolbek", "kolbekot", "kolbekov", "kolbekon", "promise", "promiseto", "promisevo", "promiseno", "asinhroно", "sinhroно",
    "mreža", "mrežata", "mrežava", "mrežana", "protokol", "protokolot", "protokolov", "protokolon",
    "porta", "portata", "portava", "portana", "host", "hostot", "hostov", "hoston",
    "domen", "domenot", "domenov", "domenon", "URL", "pateka", "patekata", "patekava", "patekana",
    "parametri", "zaglavja", "teloto na baranjeto", "status kod", "greška", "greškata", "greškava", "greškana", 
    "uspeh", "uspehot", "uspehov", "uspehon",

    // English
    "code", "function", "variable", "class", "loop", "if", "else", "array",
    "object", "string", "integer", "boolean", "true", "false", "import", "export",
    "console", "log", "compile", "run", "execute", "return", "cycle", "print", "test",
    "algorithm", "input", "output", "program", "developer", "software", "hardware",
    "logic", "bug", "fix", "error", "correct", "submit", "challenge", "IDE", "editor",
    "terminal", "keyboard", "compile error", "syntax", "framework", "database",
    "server", "client", "language", "platform", "application", "interface", "library",
    "structure", "method", "constructor", "record", "statement", "question", "solution",
    "user", "form", "task", "web", "page", "link", "request", "response", "tool",
    "list", "json", "key", "value", "input data", "output data", "git", "github",
    "feature", "comment", "explanation", "debug", "define", "solve",
    // Added new words
    "sorting", "searching", "filtering", "mapping", "iteration", "recursion",
    "matrix", "table", "row", "column", "index", "length", "size", "dimension",
    "password", "username", "login", "logout", "session", "token", "encryption",
    "validation", "check", "condition", "criteria", "parameter", "argument",
    "return value", "exception", "throw error", "error handling",
    "optimization", "performance", "speed", "memory", "space", "time",
    "binary", "hexadecimal", "decimal", "bit", "byte", "megabyte", "gigabyte",
    "compression", "decompression", "encoding", "decoding", "hash", "cipher",
    "instance", "inheritance", "encapsulation", "polymorphism",
    "abstraction", "module", "package", "namespace", "scope", "visibility",
    "static", "dynamic", "public", "private", "protected", "constant",
    "statistics", "analysis", "report", "chart", "diagram", "visualization",
    "testing", "unit test", "integration test", "functional test",
    "automation", "script", "macro", "command", "command line arguments",
    "configuration", "settings", "options", "flag", "switch", "mode",
    "development", "production", "testing", "version", "revision", "commit",
    "branch", "merge", "conflict", "resolution", "repository",
    "documentation", "manual", "help", "guide", "tutorial", "example",
    "demo", "mockup", "prototype", "schema", "model", "architecture", "design",
    "pattern", "template", "style", "theme", "appearance", "interface",
    "button", "form", "field", "list", "menu", "navigation", "routes", "pages",
    "component", "widget", "element", "attribute", "property", "value",
    "event", "handler", "callback", "promise", "asynchronous", "synchronous",
    "network", "protocol", "port", "host", "domain", "URL", "path", "parameters",
    "headers", "request body", "status code", "error", "success",

    // Programming languages
    "javascript", "python", "java", "csharp", "c#", "c++", "cpp", "html", "css", "php",
    "sql", "typescript", "react", "vue", "angular", "dotnet", "aspnet", "django",
    "flask", "nodejs", "express", "tailwind", "bootstrap", "webflow"
];
